Oop homework
ArturYefriemov/green_lantern pull request #3
Opened 2020-03-18 21:46 UTC by ArturYefriemov

2020-03-19 07:44 UTC, olikhosherstov commented on lantern/oop/homework/homework.py
> +
не обов'язково вводити цей елемент  'another_food': 0

2020-03-19 07:46 UTC, olikhosherstov commented on lantern/oop/homework/homework.py
> +
у методі get потрібно вказати значення за замовчуванням. 
`self.food.get(product, 0)`

2020-03-19 07:52 UTC, olikhosherstov commented on lantern/oop/homework/homework.py
> +
метод `_reduce_saturation_level` має працювати тільки зі змінною класу saturation_level, а не повертати якесь значення. Має бути:
```
        if self.saturation_level < 0:
            self.saturation_level = 0
```
найоптимальнішій шлях використати вбудовану функцію max():
```
    def _reduce_saturation_level(self, value):
        self.saturation_level = max(self.saturation_level - value, 0)
```

2020-03-19 07:54 UTC, olikhosherstov commented on lantern/oop/homework/homework.py
> +
метод `_increase_saturation_level` має працювати тільки зі змінною класу saturation_level, а не повертати якесь значення. Має бути:
```
        if self.saturation_level > 100:
            self.saturation_level = 100
```
найоптимальнішій шлях використати вбудовану функцію min():
```
    def _increase_saturation_level(self, value):
        self.saturation_level = min(self.saturation_level + value, 100)
```

2020-03-19 07:56 UTC, olikhosherstov commented on lantern/oop/homework/homework.py
> +            return 9
В даному випадку порогове значення 7 вже враховано у попередній умові. Коректним буде:
```
        if self.age <= 7:
            return 12
        elif self.age <= 10:
            return 9
```

2020-03-19 08:06 UTC, olikhosherstov commented on lantern/oop/homework/homework.py
> +
Метод має повертати не тільки повідомлення про смерть кота, але й значення змінної saturation_level, що зберігає рівень насиченості:
```
    def get_saturation_level(self):
        if self.saturation_level > 0:
            return self.saturation_level
        else:
            return 'Your cat is dead :('
```
Ця умова може бути видозмінена до:
```
    def get_saturation_level(self):
        return self.saturation_level if self.saturation_level > 0 else "Your cat is died :("
```

2020-03-19 08:07 UTC, olikhosherstov commented on lantern/oop/homework/homework.py
> +
'another_food': 0 по анології з класом Cat цей єлемент не потрібен.

2020-03-19 08:08 UTC, olikhosherstov commented on lantern/oop/homework/homework.py
> +
По аналогії з класом Cat у методі get вказати значення за замовчуванням.

2020-03-19 08:09 UTC, olikhosherstov commented on lantern/oop/homework/homework.py
> +
По аналогії з класом Cat порогове значення 5 вже враховано у попередній умові.

2020-03-19 08:24 UTC, olikhosherstov commented on lantern/oop/homework/homework.py
> +            raise ValueError("Our house can not have more than 4 walls")
Умовамає бути:
`if len(self.__walls) ==4:`

2020-03-19 08:30 UTC, olikhosherstov commented on lantern/oop/homework/homework.py
> +            raise ValueError("Value must be not 0")
краще розширити умову до:
(width or height) <= 0: 
тоді у обчислення не проскочуть від'ємні атрибути.

2020-03-19 08:31 UTC, olikhosherstov commented on lantern/oop/homework/homework.py
> +            raise ValueError("Value must be not 0")
краще розширити умову до:
(width or height) <= 0:

2020-03-19 08:38 UTC, olikhosherstov commented on lantern/oop/homework/homework.py
> +        return sum([wall.wall_square()for wall in self.__walls])
Пробіл перед for.

2020-03-19 08:50 UTC, olikhosherstov commented on lantern/oop/homework/homework.py
> +                       for number_rolls in self.__walls)
раджу називати екземпляри класів асоціативними назвами. Щоб не заплутатись у майбутньому. ) Як приклад:
`for wall in self.__walls`
`for side in self.__walls`
`for block in self.__walls`

2020-03-20 11:57 UTC, dimigor requested changes

2020-03-20 11:57 UTC, dimigor commented on lantern/oop/homework/homework.py
> +
Raise an exception if cat was died

2020-03-22 10:09 UTC, dimigor approved these changes

2020-03-23 15:29 UTC, merged